### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Awesomeloper** [MaaSTaaR/PrettyPi#2]
I get the following (RPi 4 8GB Python 3.7)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 325, in __call__
    self._flush_bg_loading_exception()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 313, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 302, in _load_app
    self._load_unlocked()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
File "/home/pi/PrettyPi/control/app.py", line 125
    print workingTask;
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(workingTask)?

Is this due to wrong Python version? If so, how do I use explicitly a different version for this script? Also, the run.sh won't execute.

**Comment by MaaSTaaR** [comment]
Fixed.
